name: SSH into Server and Run ls

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: 3.136.116.231
          username: ubuntu
          key: ${{ SSH }}
          script: |
            ls -la
